services:
  - type: web
    name: petstore-backend
    runtime: docker
    plan: free
    healthCheckPath: /alonzo/api/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: petstore-postgres
          property: connectionString

static_sites:
  - name: petstore-frontend
    plan: free
    staticPublishPath: ./frontend/dist
    buildCommand: cd frontend && npm install && npm run build

databases:
  - name: petstore-postgres
    databaseName: petstore_db
    user: petstore_user
    plan: free
